USE portfolio_analyzer;

-- Add new columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS career_objective TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin VARCHAR(255) DEFAULT NULL;

-- Add new columns to projects table
ALTER TABLE projects ADD COLUMN IF NOT EXISTS technologies VARCHAR(255) DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS github_link VARCHAR(255) DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS live_demo VARCHAR(255) DEFAULT NULL;
